version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./stock_db:/var/lib/mysql
    ports:
      - 3306:3306

