server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mariadb://localhost:3306/stock
    username: root
    password: example
    driver-class-name: org.mariadb.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2
